name: AWS S3

on:
  push:
    tags: 
      - v[0-9].[0-9].[0-9]

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.1'
          extended: true  

      - name: S3 upload (images)
        run: aws s3 sync --acl public-read --follow-symlinks static/shared s3://$AWS_S3_BUCKET/shared/ --delete

      - name: Remove static images
        shell: bash
        run: |
          cd static && rm -rf shared

      - name: Installing Dependencies
        run: npm install

      - id: version
        run: echo "::set-output name=release_tag::$(echo $GITHUB_REF | sed -E "s/refs\/tags\/(v[1-9]+\.[0-9]+)\.[0-9]+/\1/g" )"
        shell: bash

      - name: Config latest path
        run: cd config/_default && sed -i -E "s/latest_path = /latest_path = \$VERSION/g" config.toml
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: Build
        run: npm run build-playground && hugo -D --minify -b $BASE_URL/$VERSION
        env: 
          BASE_URL: https://docs.usebeagle.io
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: S3 upload (latest version)
        run: aws s3 sync --acl public-read --follow-symlinks public s3://$AWS_S3_BUCKET/$VERSION/ --delete
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: Config Proxy
        run: sed -i "s/\${latest_version}/$VERSION/" .github/workflows/proxy/index.html
        shell: bash
        env:
          VERSION: ${{ steps.version.outputs.release_tag }}

      - name: S3 upload (redirect to latest version)
        run: aws s3 sync --acl public-read --follow-symlinks .github/workflows/proxy s3://$AWS_S3_BUCKET